import { Router } from 'express'
import { z } from 'zod'
import { pool } from '../db/pool.js'
import { requireAuth, requireRole } from '../middleware/auth.js'

const router = Router()
const id = z.string().uuid()
const meetingSchema = z.object({ studentId: id, title: z.string().trim().min(1).max(180), description: z.string().trim().max(3000).optional(), scheduledStart: z.coerce.date(), scheduledEnd: z.coerce.date(), location: z.string().trim().max(255).optional(), meetingType: z.string().trim().min(1).max(50) }).refine((input) => input.scheduledEnd > input.scheduledStart, { message: 'scheduledEnd must be after scheduledStart' })

async function mentorIdForUser(userId: string) { const result = await pool.query<{ id: string }>('SELECT id FROM faculty WHERE user_id = $1 AND status = \'ACTIVE\'', [userId]); return result.rows[0]?.id }
async function ownsStudent(mentorUserId: string, studentId: string) { const result = await pool.query('SELECT 1 FROM mentor_assignments ma JOIN faculty f ON f.id = ma.mentor_id WHERE ma.student_id = $1 AND f.user_id = $2 AND ma.status = \'ACTIVE\'', [studentId, mentorUserId]); return Boolean(result.rowCount) }

router.post('/', requireAuth, requireRole('ADMIN', 'MENTOR'), async (request, response, next) => { try { const input = meetingSchema.parse(request.body); if (!(await ownsStudent(request.auth!.userId, input.studentId))) return response.status(403).json({ success: false, error: { code: 'FORBIDDEN', message: 'Student is outside your access scope' } }); const mentorId = await mentorIdForUser(request.auth!.userId); if (!mentorId) return response.status(422).json({ success: false, error: { code: 'FACULTY_PROFILE_REQUIRED', message: 'An active faculty profile is required' } }); const result = await pool.query<{ id: string }>('INSERT INTO mentor_meetings (mentor_id, student_id, title, description, scheduled_start, scheduled_end, location, meeting_type, status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,\'SCHEDULED\') RETURNING id', [mentorId, input.studentId, input.title, input.description ?? null, input.scheduledStart, input.scheduledEnd, input.location ?? null, input.meetingType]); return response.status(201).json({ success: true, data: { id: result.rows[0].id }, message: 'Meeting scheduled' }) } catch (error) { next(error) } })

router.get('/', requireAuth, requireRole('ADMIN', 'MENTOR', 'STUDENT'), async (request, response, next) => { try { const values: string[] = []; let scope = ''; if (request.auth!.roles.includes('STUDENT')) { values.push(request.auth!.userId); scope = `JOIN students s ON s.id = m.student_id AND s.user_id = $${values.length}` } else if (request.auth!.roles.includes('MENTOR') && !request.auth!.roles.includes('ADMIN')) { values.push(request.auth!.userId); scope = `JOIN faculty f ON f.id = m.mentor_id AND f.user_id = $${values.length}` } const result = await pool.query(`SELECT m.id, m.title, m.description, m.scheduled_start, m.scheduled_end, m.location, m.meeting_type, m.status, m.notes, m.action_items, m.student_id, m.mentor_id FROM mentor_meetings m ${scope} ORDER BY m.scheduled_start DESC LIMIT 100`, values); return response.json({ success: true, data: result.rows, message: 'Meetings loaded' }) } catch (error) { next(error) } })

router.patch('/:id', requireAuth, requireRole('ADMIN', 'MENTOR'), async (request, response, next) => { try { const meetingId = id.parse(request.params.id); const input = z.object({ status: z.enum(['SCHEDULED', 'COMPLETED', 'CANCELLED']).optional(), notes: z.string().max(5000).nullable().optional(), actionItems: z.string().max(5000).nullable().optional() }).parse(request.body); const mentorId = await mentorIdForUser(request.auth!.userId); const result = await pool.query(`UPDATE mentor_meetings SET status = COALESCE($1, status), notes = COALESCE($2, notes), action_items = COALESCE($3, action_items), updated_at = now() WHERE id = $4 AND ($5 = true OR mentor_id = $6) RETURNING id, status, notes, action_items`, [input.status ?? null, input.notes ?? null, input.actionItems ?? null, meetingId, request.auth!.roles.includes('ADMIN'), mentorId ?? null]); if (!result.rowCount) return response.status(403).json({ success: false, error: { code: 'FORBIDDEN', message: 'Meeting is outside your access scope' } }); return response.json({ success: true, data: result.rows[0], message: 'Meeting updated' }) } catch (error) { next(error) } })
export default router
