import { Router } from 'express'
import { z } from 'zod'
import { pool } from '../db/pool.js'
import { requireAuth, requireRole } from '../middleware/auth.js'

const router = Router()
const id = z.string().uuid()
const assignmentSchema = z.object({ mentorId: id, studentId: id, effectiveFrom: z.coerce.date(), effectiveUntil: z.coerce.date().optional() }).refine((input) => !input.effectiveUntil || input.effectiveUntil > input.effectiveFrom, { message: 'effectiveUntil must be after effectiveFrom' })

router.get('/', requireAuth, requireRole('ADMIN'), async (_request, response, next) => { try { const result = await pool.query('SELECT ma.id, ma.mentor_id, ma.student_id, ma.assigned_at, ma.effective_from, ma.effective_until, ma.status, mu.first_name || \' \' || mu.last_name AS mentor_name, su.first_name || \' \' || su.last_name AS student_name, s.student_register_number FROM mentor_assignments ma JOIN faculty f ON f.id = ma.mentor_id JOIN users mu ON mu.id = f.user_id JOIN students s ON s.id = ma.student_id JOIN users su ON su.id = s.user_id ORDER BY ma.created_at DESC LIMIT 500'); return response.json({ success: true, data: result.rows, message: 'Mentor assignments loaded' }) } catch (error) { next(error) } })

router.post('/', requireAuth, requireRole('ADMIN'), async (request, response, next) => { const client = await pool.connect(); try { const input = assignmentSchema.parse(request.body); await client.query('BEGIN'); const valid = await client.query('SELECT 1 FROM faculty f JOIN students s ON s.id = $2 WHERE f.id = $1 AND f.status = \'ACTIVE\' AND s.status = \'ACTIVE\'', [input.mentorId, input.studentId]); if (!valid.rowCount) { await client.query('ROLLBACK'); return response.status(422).json({ success: false, error: { code: 'INVALID_ASSIGNMENT', message: 'Active mentor and student profiles are required' } }) } await client.query('UPDATE mentor_assignments SET status = \'ENDED\', effective_until = COALESCE(effective_until, $1), updated_at = now() WHERE student_id = $2 AND status = \'ACTIVE\'', [input.effectiveFrom, input.studentId]); const created = await client.query<{ id: string }>('INSERT INTO mentor_assignments (mentor_id, student_id, assigned_by, effective_from, effective_until, status) VALUES ($1,$2,$3,$4,$5,\'ACTIVE\') RETURNING id', [input.mentorId, input.studentId, request.auth!.userId, input.effectiveFrom, input.effectiveUntil ?? null]); await client.query('COMMIT'); return response.status(201).json({ success: true, data: { id: created.rows[0].id }, message: 'Mentor assigned' }) } catch (error) { await client.query('ROLLBACK'); next(error) } finally { client.release() } })

router.patch('/:id/end', requireAuth, requireRole('ADMIN'), async (request, response, next) => { try { const assignmentId = id.parse(request.params.id); const result = await pool.query('UPDATE mentor_assignments SET status = \'ENDED\', effective_until = COALESCE(effective_until, now()), updated_at = now() WHERE id = $1 AND status = \'ACTIVE\' RETURNING id, status, effective_until', [assignmentId]); if (!result.rowCount) return response.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Active assignment not found' } }); return response.json({ success: true, data: result.rows[0], message: 'Assignment ended' }) } catch (error) { next(error) } })
export default router
