import { useState, type ChangeEvent } from 'react'
import { Check, Clipboard, Eye, FileSpreadsheet, Plus, Sparkles, Trophy, Trash2 } from 'lucide-react'
import type { LeaderboardRow, QuizSummary } from './api/client'

type DraftQuestion = { text: string; type: 'MCQ' | 'FILL_BLANK' | 'TRUE_FALSE' | 'SHORT_ANSWER'; options: string[]; correct: number; expectedAnswer: string; marks: number }
type TeacherView = 'dashboard' | 'quizzes' | 'results'
type Props = { view: TeacherView; quizzes: QuizSummary[]; leaderboards: Record<string, LeaderboardRow[]>; publishedCode: string; copied: boolean; title: string; instructions: string; duration: number; questions: DraftQuestion[]; message: string; busy: boolean; setView: (view: TeacherView) => void; setTitle: (value: string) => void; setInstructions: (value: string) => void; setDuration: (value: number) => void; setQuestions: (value: DraftQuestion[]) => void; onCopy: () => void; onShare: () => void; onSave: () => void; onPublish: () => void; onSignOut: () => void }
const emptyQuestion = (): DraftQuestion => ({ text: '', type: 'MCQ', options: ['', '', '', ''], correct: 0, expectedAnswer: '', marks: 1 })

export function TeacherWorkspace({ view, quizzes, leaderboards, publishedCode, copied, title, instructions, duration, questions, message, busy, setView, setTitle, setInstructions, setDuration, setQuestions, onCopy, onShare, onSave, onPublish, onSignOut }: Props) {
  const [deleted, setDeleted] = useState('')
  const [importStatus, setImportStatus] = useState('')
  const [selectedQuizId, setSelectedQuizId] = useState('all')
  const publishedQuizzes = quizzes.filter((quiz) => quiz.status !== 'DRAFT')
  const selectedLeaderboard = selectedQuizId ? leaderboards[selectedQuizId] ?? [] : []
  const updateQuestion = (index: number, next: DraftQuestion) => setQuestions(questions.map((item, itemIndex) => itemIndex === index ? next : item))
  return <section className="teacher-layout">
    <aside className="teacher-nav"><p className="eyebrow">Teacher workspace</p><h1>Make a room<br />for thinking.</h1><button className={`nav-link ${view === 'dashboard' ? 'active' : ''}`} onClick={() => setView('dashboard')}>Dashboard</button><button className={`nav-link ${view === 'quizzes' ? 'active' : ''}`} onClick={() => setView('quizzes')}>My quizzes</button><button className={`nav-link ${view === 'results' ? 'active' : ''}`} onClick={() => setView('results')}>Results</button><button className="nav-link" onClick={onSignOut}>Sign out</button></aside>
    <div className="teacher-content"><div className="teacher-heading"><div><p className="eyebrow">Your classroom</p><h2>{view === 'results' ? 'Results' : view === 'quizzes' ? 'My quizzes' : 'Build a quiz'}</h2></div></div>
      {view === 'dashboard' && <section className="editor"><label>Quiz title *<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Java Basics" required /></label><label>Instructions<textarea value={instructions} onChange={(event) => setInstructions(event.target.value)} rows={3} /></label><label>Duration (minutes)<input type="number" min="1" max="480" value={duration} onChange={(event) => setDuration(Number(event.target.value))} /></label><div className="section-heading"><div><p className="eyebrow">Questions</p><h3>Add your questions</h3><small className="import-help">Import a spreadsheet with columns: Question, Type, Option A-D, Answer, Marks.</small></div><div className="question-actions"><label className="button button-secondary small import-button"><FileSpreadsheet size={15} /> Import Excel<input type="file" accept=".xlsx,.xls" onChange={(event) => void importQuestions(event, questions, setQuestions, setImportStatus)} /></label><button type="button" className="button button-secondary small" onClick={() => setQuestions([...questions, emptyQuestion()])}><Plus size={15} /> Add question</button></div></div>{questions.map((question, index) => <QuestionEditor key={index} index={index} question={question} onChange={(next) => updateQuestion(index, next)} onDelete={() => { setQuestions(questions.filter((_, itemIndex) => itemIndex !== index)); setDeleted('Question deleted.') }} />)}{message && <p className="form-message" role="status">{message}</p>}{deleted && <p className="success-message" role="status">{deleted}</p>}{importStatus && <p className={importStatus.startsWith('Imported') ? 'success-message' : 'form-message'} role="status">{importStatus}</p>}<div className="editor-actions"><button type="button" className="button button-quiet" onClick={onSave} disabled={busy}>Save draft</button><button type="button" className="button button-primary" onClick={onPublish} disabled={busy}><Sparkles size={16} />{busy ? 'Publishing...' : 'Publish quiz'}</button></div></section>}
      {view === 'quizzes' && <QuizList quizzes={quizzes} publishedCode={publishedCode} copied={copied} onCopy={onCopy} onShare={onShare} onCreate={() => setView('dashboard')} />}
      {view === 'results' && <ResultsByQuiz quizzes={publishedQuizzes} selectedQuizId={selectedQuizId} selectedLeaderboard={selectedLeaderboard} onSelect={setSelectedQuizId} />}
    </div>
  </section>
}

function QuestionEditor({ index, question, onChange, onDelete }: { index: number; question: DraftQuestion; onChange: (question: DraftQuestion) => void; onDelete: () => void }) {
  const isChoice = question.type === 'MCQ'
  return <article className="question-editor"><div className="question-top"><strong>Question {index + 1}</strong><button type="button" className="icon-button" onClick={onDelete} aria-label={`Delete question ${index + 1}`}><Trash2 size={16} /></button></div><label>Type<select value={question.type} onChange={(event) => { const type = event.target.value as DraftQuestion['type']; onChange({ ...question, type, options: type === 'MCQ' ? ['', '', '', ''] : [] }) }}><option value="MCQ">Multiple choice</option><option value="FILL_BLANK">Fill in the blank</option><option value="TRUE_FALSE">True / false</option><option value="SHORT_ANSWER">Short answer</option></select></label><label>Question<input value={question.text} onChange={(event) => onChange({ ...question, text: event.target.value })} placeholder="Enter your question" /></label>{isChoice ? question.options.map((option, optionIndex) => <label className="option-row" key={optionIndex}><input type="radio" name={`correct-${index}`} checked={question.correct === optionIndex} onChange={() => onChange({ ...question, correct: optionIndex })} aria-label={`Mark option ${String.fromCharCode(65 + optionIndex)} correct`} /><input value={option} onChange={(event) => onChange({ ...question, options: question.options.map((item, itemIndex) => itemIndex === optionIndex ? event.target.value : item) })} placeholder={`Option ${String.fromCharCode(65 + optionIndex)}`} /></label>) : question.type !== 'SHORT_ANSWER' && <label>Expected answer<input value={question.expectedAnswer} onChange={(event) => onChange({ ...question, expectedAnswer: event.target.value })} placeholder={question.type === 'TRUE_FALSE' ? 'True or False' : 'Expected answer'} /></label>}<label className="marks-field">Marks<input type="number" min="1" value={question.marks} onChange={(event) => onChange({ ...question, marks: Number(event.target.value) })} /></label></article>
}

function cell(row: Record<string, unknown>, names: string[]) { const entries = Object.entries(row); const match = entries.find(([key]) => names.includes(key.toLowerCase().replace(/[^a-z0-9]/g, ''))); return String(match?.[1] ?? '').trim() }
function importedType(value: string): DraftQuestion['type'] { const normalized = value.toUpperCase().replace(/[^A-Z]/g, '_'); if (normalized.includes('TRUE')) return 'TRUE_FALSE'; if (normalized.includes('FILL')) return 'FILL_BLANK'; if (normalized.includes('SHORT')) return 'SHORT_ANSWER'; return 'MCQ' }
async function importQuestions(event: ChangeEvent<HTMLInputElement>, currentQuestions: DraftQuestion[], setQuestions: (questions: DraftQuestion[]) => void, setStatus: (status: string) => void) {
  const file = event.target.files?.[0]
  event.target.value = ''
  if (!file) return
  try {
    const XLSX = await import('xlsx')
    const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' })
    const firstSheet = workbook.Sheets[workbook.SheetNames[0]]
    const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(firstSheet, { defval: '' })
    const imported = rows.map((row) => {
      const text = cell(row, ['question', 'text', 'questiontext'])
      const type = importedType(cell(row, ['type', 'questiontype']))
      const options = ['a', 'b', 'c', 'd'].map((letter) => cell(row, [`option${letter}`, letter])).filter(Boolean)
      const answer = cell(row, ['answer', 'correct', 'correctanswer', 'expectedanswer'])
      const correct = Math.max(0, options.findIndex((option, index) => answer.toUpperCase() === String.fromCharCode(65 + index) || answer.toLowerCase() === option.toLowerCase()))
      return { text, type, options: type === 'MCQ' ? options : [], correct, expectedAnswer: type === 'MCQ' ? '' : answer, marks: Number(cell(row, ['marks', 'points'])) || 1 }
    }).filter((question) => question.text)
    if (!imported.length) throw new Error('No rows with a Question column were found.')
    setQuestions([...currentQuestions.filter((question) => question.text.trim()), ...imported])
    setStatus(`Imported ${imported.length} question${imported.length === 1 ? '' : 's'} from ${file.name}.`)
  } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to read that Excel file.') }
}

function QuizList({ quizzes, publishedCode, copied, onCopy, onShare, onCreate }: { quizzes: QuizSummary[]; publishedCode: string; copied: boolean; onCopy: () => void; onShare: () => void; onCreate: () => void }) { return <section className="quiz-list"><div className="section-heading"><div><p className="eyebrow">Your quizzes</p><h3>Published rooms</h3></div><span>{quizzes.length} total</span></div>{publishedCode && <div className="code-card"><p className="eyebrow">Quiz published</p><strong>Your quiz code</strong><b>{publishedCode}</b><div className="code-actions"><button type="button" className="button button-secondary" onClick={onCopy}>{copied ? <><Check size={15} /> Copied</> : <><Clipboard size={15} /> Copy code</>}</button><button type="button" className="button button-secondary" onClick={onShare}>Copy share link</button></div><small>Students can open the share link or enter the code.</small></div>}{quizzes.length ? quizzes.map((quiz) => <article className="quiz-list-item" key={quiz.id}><div><strong>{quiz.title}</strong><span>{quiz.total_marks} marks · {quiz.status}</span></div><b>{quiz.join_code ?? 'No code'}</b></article>) : <div className="empty-state"><p>No quizzes yet.</p><span>Create your first quiz to get started.</span><button type="button" className="button button-primary" onClick={onCreate}>Create quiz</button></div>}</section> }
function ResultsByQuiz({ quizzes, selectedQuizId, selectedLeaderboard, onSelect }: { quizzes: QuizSummary[]; selectedQuizId: string; selectedLeaderboard: LeaderboardRow[]; onSelect: (quizId: string) => void }) { return <div className="results-module"><div className="results-quiz-grid">{quizzes.length ? quizzes.map((quiz) => <article className={`result-quiz-card ${selectedQuizId === quiz.id ? 'selected' : ''}`} key={quiz.id}><div className="result-quiz-icon"><Trophy size={18} /></div><div className="result-quiz-copy"><p className="eyebrow">{quiz.status}</p><h3>{quiz.title}</h3><span>{quiz.total_marks} marks · {quiz.duration_minutes} minutes</span></div><button type="button" className="button button-secondary small" onClick={() => onSelect(selectedQuizId === quiz.id ? '' : quiz.id)}><Eye size={15} />{selectedQuizId === quiz.id ? 'Hide leaderboard' : 'View leaderboard'}</button></article>) : <div className="empty-state"><p>No published quizzes yet.</p><span>Publish a quiz to see its results here.</span></div>}</div>{selectedQuizId && <LeaderboardPanel rows={selectedLeaderboard} />}</div> }
function LeaderboardPanel({ rows }: { rows: LeaderboardRow[] }) { return <section className="leaderboard-panel"><div className="section-heading"><div><p className="eyebrow">Live ranking</p><h3>Leaderboard</h3></div><span>{rows.length} ranked</span></div>{rows.length ? <div className="leaderboard-table">{rows.map((row) => <div className="leaderboard-row" key={`${row.rank}-${row.name}`}><b>#{row.rank}</b><strong>{row.name}</strong><span>{row.obtained_marks}/{row.total_marks}</span><em>{row.percentage}%</em></div>)}</div> : <div className="empty-state"><p>No ranked submissions yet.</p><span>Results appear here after students submit.</span></div>}</section> }
